-- CLEAN RESET (Agar tidak ada konflik constraint/struktur lama)
drop table if exists dish_ingredients cascade;
drop table if exists menu_dishes cascade;
drop table if exists daily_menus cascade;
drop table if exists caterings cascade;

-- 1. Buat Tabel Master Catering
create table caterings (
  id bigint generated by default as identity primary key,
  name text not null unique, -- Pastikan ada UNIQUE constraint
  address text,
  contact_person text,
  phone text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for caterings
alter table caterings enable row level security;
create policy "Enable all access for caterings" on caterings for all using (true) with check (true);

-- 2. Isi Data Awal Catering
insert into caterings (name) values 
  ('Catering Sehat'), 
  ('Catering Berkah'), 
  ('Dapur Mama')
on conflict (name) do nothing;

-- 3. Tabel Header Menu Harian (Updated with catering_id)
create table daily_menus (
  id bigint generated by default as identity primary key,
  
  catering_id bigint references caterings(id) on delete cascade not null,
  
  date date not null,
  meal_time text not null, -- 'Pagi', 'Siang', 'Malam', 'Snack Pagi', 'Snack Sore'
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Unik berdasarkan Tanggal + Waktu + Catering
  unique(date, meal_time, catering_id)
);

-- Tabel Masakan
create table menu_dishes (
  id bigint generated by default as identity primary key,
  menu_id bigint references daily_menus(id) on delete cascade,
  name text not null, 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabel Bahan Makanan
create table dish_ingredients (
  id bigint generated by default as identity primary key,
  dish_id bigint references menu_dishes(id) on delete cascade,
  
  ingredient_id bigint references ingredients_library(id),
  ingredient_name text not null, 
  
  weight_cooked numeric, 
  weight_raw numeric not null default 0, 
  weight_net numeric not null default 0, 
  
  conversion_factor numeric default 1.0, 
  bdd_percent numeric default 100, 
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Re-Enable RLS Policies
alter table daily_menus enable row level security;
alter table menu_dishes enable row level security;
alter table dish_ingredients enable row level security;

create policy "Enable all access for daily_menus" on daily_menus for all using (true) with check (true);
create policy "Enable all access for menu_dishes" on menu_dishes for all using (true) with check (true);
create policy "Enable all access for dish_ingredients" on dish_ingredients for all using (true) with check (true);
