-- Schema untuk Tabel Faktor Konversi
-- Menyimpan data faktor konversi bahan makanan (matang -> mentah)

-- Tabel CONVERSION_FACTORS
create table conversion_factors (
  id bigint generated by default as identity primary key,
  food_name text not null,                    -- Nama Bahan Makanan
  conversion_factor numeric default 1.0,      -- Faktor Konversi (Mentah)
  bdd_percent numeric default 100,            -- Berat Dapat Dimakan (%)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index untuk pencarian
create index idx_conversion_factors_food_name on conversion_factors(food_name);

-- Trigger untuk update timestamp
create or replace function update_conversion_factors_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

create trigger trigger_update_conversion_factors_updated_at
  before update on conversion_factors
  for each row
  execute function update_conversion_factors_updated_at();

-- Enable RLS (Row Level Security) - Optional
alter table conversion_factors enable row level security;

-- Policy untuk membaca (public read)
create policy "Enable read access for all users" on conversion_factors
  for select using (true);

-- Policy untuk insert/update/delete (authenticated users only)
create policy "Enable insert for authenticated users only" on conversion_factors
  for insert with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" on conversion_factors
  for update using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only" on conversion_factors
  for delete using (auth.role() = 'authenticated');
