-- Create Master Table for Meal Types
create table if not exists public.meal_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  emoji text,
  sort_order int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.meal_types enable row level security;

-- Policies
create policy "Enable read access for all users" on public.meal_types for select using (true);
create policy "Enable insert for authenticated users only" on public.meal_types for insert with check (auth.role() = 'authenticated');
create policy "Enable update for authenticated users only" on public.meal_types for update using (auth.role() = 'authenticated');
create policy "Enable delete for authenticated users only" on public.meal_types for delete using (auth.role() = 'authenticated');

-- Seed Data (Default Requirements)
insert into public.meal_types (name, emoji, sort_order) values
('Pagi', '🌅', 1),
('Siang', '☀️', 2),
('Malam', '🌙', 3),
('Snack Pagi', '☕', 4),
('Snack Sore', '☕', 5)
on conflict (name) do update set emoji = excluded.emoji;
