-- Reseting Database dengan CASCADE untuk menghapus view/dependensi terkait
drop table if exists dish_ingredients cascade;
drop table if exists menu_dishes cascade;
drop table if exists daily_menus cascade;

-- Re-Create Tables
create table daily_menus (
  id bigint generated by default as identity primary key,
  date date not null,
  meal_time text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(date, meal_time)
);

create table menu_dishes (
  id bigint generated by default as identity primary key,
  menu_id bigint references daily_menus(id) on delete cascade,
  name text not null, 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table dish_ingredients (
  id bigint generated by default as identity primary key,
  dish_id bigint references menu_dishes(id) on delete cascade,
  
  ingredient_id bigint references ingredients_library(id),
  ingredient_name text not null, 
  
  weight_cooked numeric, 
  weight_raw numeric not null default 0, 
  weight_net numeric not null default 0, 
  
  conversion_factor numeric default 1.0, 
  bdd_percent numeric default 100, 
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Re-Enable RLS
alter table daily_menus enable row level security;
alter table menu_dishes enable row level security;
alter table dish_ingredients enable row level security;

create policy "Enable all access for daily_menus" on daily_menus for all using (true) with check (true);
create policy "Enable all access for menu_dishes" on menu_dishes for all using (true) with check (true);
create policy "Enable all access for dish_ingredients" on dish_ingredients for all using (true) with check (true);
