-- Skema Database untuk Aplikasi Katering Gizi

-- 1. Tabel CATERINGS
-- Menyimpan data 4 katering (bisa ditambah)
create table caterings (
  id bigint generated by default as identity primary key,
  name text not null,
  contact_person text,
  phone text,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Tabel INGREDIENTS_LIBRARY (Database Bahan Makanan / DKBM)
-- Menyimpan standar gizi per 100g Berat Dapat Dimakan (BDD)
create table ingredients_library (
  id bigint generated by default as identity primary key,
  code text, -- Kode Bahan (e.g. AR001)
  name text not null,
  source text, -- Sumber Data (e.g. KZGMI-2001)

  
  -- Nilai Gizi per 100g BDD (Makro)
  energy_kcal numeric default 0,
  protein_g numeric default 0,
  carbs_g numeric default 0,
  fat_g numeric default 0,
  
  -- Nilai Gizi Mikro (Sesuai Image Referensi)
  water_g numeric default 0,         -- Air
  fiber_g numeric default 0,         -- Serat
  ash_g numeric default 0,           -- Abu
  calcium_mg numeric default 0,      -- Kalsium
  phosphorus_mg numeric default 0,   -- Fosfor
  iron_mg numeric default 0,         -- Besi
  sodium_mg numeric default 0,       -- Natrium
  potassium_mg numeric default 0,    -- Kalium
  copper_mg numeric default 0,       -- Tembaga
  zinc_mg numeric default 0,         -- Seng
  retinol_mcg numeric default 0,     -- Retinol
  beta_carotene_mcg numeric default 0, -- B-Kar
  total_carotene_mcg numeric default 0, -- Kar-Total
  thiamin_mg numeric default 0,      -- Thiamin (Vit B1)
  riboflavin_mg numeric default 0,   -- Riboflavin (Vit B2)
  niacin_mg numeric default 0,       -- Niasin
  vitamin_c_mg numeric default 0,    -- Vit_C
  
  -- Standar BDD (%) default
  default_bdd_percent numeric default 100,
  
  -- Optional: Faktor Konversi Matang ke Mentah (jika ada standar umum)
  default_conversion_factor numeric default 1.0 
);

-- 2b. Tabel PROCESSING_METHODS (Cara Pengolahan)
-- Menyimpan Faktor Konversi Matang ke Mentah (Fk)
-- Data Kemenkes: Nasi (0.4), Rebus (1.0), Tumis (0.9), dll.
create table processing_methods (
  id bigint generated by default as identity primary key,
  name text not null, -- e.g. "Nasi", "Rebus", "Goreng", "Tumis"
  conversion_factor numeric default 1.0, -- Faktor Konversi (Mentah / Matang)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Tabel DAILY_MENUS
-- Header untuk menu per hari, per katering, per waktu makan
create table daily_menus (
  id bigint generated by default as identity primary key,
  catering_id bigint references caterings(id) on delete cascade not null,
  menu_date date not null,
  meal_time text check (meal_time in ('Pagi', 'Siang', 'Malam')) not null,
  
  -- Target Gizi (Default 850)
  target_energy_kcal numeric default 850,
  
  -- Kesesuaian Menu (Manual Checkbox oleh Ahli Gizi)
  is_menu_compliant boolean default false,
  menu_notes text, -- Catatan tambahan jika tidak sesuai
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(catering_id, menu_date, meal_time) -- Mencegah duplikasi jadwal
);

-- 4. Tabel DISHES (Nama Menu Makanan)
-- E.g. "Nasi Putih", "Telur Ceplok Balado"
create table dishes (
  id bigint generated by default as identity primary key,
  daily_menu_id bigint references daily_menus(id) on delete cascade not null,
  name text not null, -- "Nasi Putih", "Telur Ceplok Balado"
  notes text
);

-- 5. Tabel DISH_INGREDIENTS (Komposisi Bahan & Konversi)
create table dish_ingredients (
  id bigint generated by default as identity primary key,
  dish_id bigint references dishes(id) on delete cascade not null,
  ingredient_id bigint references ingredients_library(id) not null,
  processing_method_id bigint references processing_methods(id), -- Optional, jika null assume factor 1
  
  -- Input: Berat Matang (Sesuai User Request)
  weight_cooked_g numeric not null default 0,
  
  -- Faktor-faktor (Disimpan agar history tidak berubah jika master berubah)
  bdd_percent numeric default 100, -- Dari Ingredient
  conversion_factor numeric default 1.0, -- Dari Processing Method (Mentah / Matang)
  
  -- Hasil Perhitungan
  -- 1. Berat Mentah Kotor = Berat Matang * Faktor Konversi
  weight_raw_gross_g numeric generated always as (weight_cooked_g * conversion_factor) stored,
  
  -- 2. Berat Mentah Bersih (BDD) = Berat Mentah Kotor * (BDD/100)
  -- Ini yang dikalikan dengan Data Komposisi Pangan
  weight_raw_net_g numeric generated always as ((weight_cooked_g * conversion_factor) * (bdd_percent/100.0)) stored,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Tabel REFERENCE_STANDARDS (Tetap sama, tidak diubah)
create table reference_standards (
  id bigint generated by default as identity primary key,
  name text not null, -- e.g. "Standar Umum", "Standar Diet X"
  
  -- Target Harian
  energy_kcal numeric default 2550,
  protein_g numeric default 65,
  fat_g numeric default 70,
  carbs_g numeric default 415,
  fiber_g numeric default 36,
  water_g numeric default 2500,
  calcium_mg numeric default 1000,
  phosphorus_mg numeric default 700,
  iron_mg numeric default 9,
  sodium_mg numeric default 1500,
  potassium_mg numeric default 4700,
  copper_mg numeric default 90, -- check unit in image
  zinc_mg numeric default 11,
  thiamin_mg numeric default 1.2, -- estimated standard
  riboflavin_mg numeric default 1.3,
  niacin_mg numeric default 16,
  vitamin_c_mg numeric default 90,
  
  is_active boolean default true
);

-- View untuk memudahkan Query Total Gizi (Updated columns)
create or replace view view_menu_nutrition as
select 
  dm.id as daily_menu_id,
  dm.menu_date,
  dm.meal_time,
  c.name as catering_name,
  -- Makro
  sum((di.weight_raw_net_g / 100.0) * il.energy_kcal) as total_energy_kcal,
  sum((di.weight_raw_net_g / 100.0) * il.protein_g) as total_protein_g,
  sum((di.weight_raw_net_g / 100.0) * il.carbs_g) as total_carbs_g,
  sum((di.weight_raw_net_g / 100.0) * il.fat_g) as total_fat_g,
  -- Mikro
  sum((di.weight_raw_net_g / 100.0) * il.water_g) as total_water_g,
  sum((di.weight_raw_net_g / 100.0) * il.fiber_g) as total_fiber_g,
  sum((di.weight_raw_net_g / 100.0) * il.ash_g) as total_ash_g,
  sum((di.weight_raw_net_g / 100.0) * il.calcium_mg) as total_calcium_mg,
  sum((di.weight_raw_net_g / 100.0) * il.phosphorus_mg) as total_phosphorus_mg,
  sum((di.weight_raw_net_g / 100.0) * il.iron_mg) as total_iron_mg,
  sum((di.weight_raw_net_g / 100.0) * il.sodium_mg) as total_sodium_mg,
  sum((di.weight_raw_net_g / 100.0) * il.potassium_mg) as total_potassium_mg,
  sum((di.weight_raw_net_g / 100.0) * il.copper_mg) as total_copper_mg,
  sum((di.weight_raw_net_g / 100.0) * il.zinc_mg) as total_zinc_mg,
  sum((di.weight_raw_net_g / 100.0) * il.retinol_mcg) as total_retinol_mcg,
  sum((di.weight_raw_net_g / 100.0) * il.beta_carotene_mcg) as total_beta_carotene_mcg,
  sum((di.weight_raw_net_g / 100.0) * il.total_carotene_mcg) as total_total_carotene_mcg,
  sum((di.weight_raw_net_g / 100.0) * il.thiamin_mg) as total_thiamin_mg,
  sum((di.weight_raw_net_g / 100.0) * il.riboflavin_mg) as total_riboflavin_mg,
  sum((di.weight_raw_net_g / 100.0) * il.niacin_mg) as total_niacin_mg,
  sum((di.weight_raw_net_g / 100.0) * il.vitamin_c_mg) as total_vitamin_c_mg,

  dm.target_energy_kcal,
  dm.is_menu_compliant, -- Kolom baru untuk validasi manual
  case 
    when sum((di.weight_raw_net_g / 100.0) * il.energy_kcal) >= dm.target_energy_kcal then true 
    else false 
  end as is_target_met_auto
from daily_menus dm
join caterings c on dm.catering_id = c.id
join dishes d on d.daily_menu_id = dm.id
join dish_ingredients di on di.dish_id = d.id
join ingredients_library il on di.ingredient_id = il.id
group by dm.id, dm.menu_date, dm.meal_time, c.name, dm.target_energy_kcal;
